[package]
name = "changesette"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
description = "A version and changelog manager for single-package applications, using the changesets file format"
repository = "https://github.com/iorate/changesette"
license = "MIT"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
dialoguer = "0.12.0"
jsonc-parser = { version = "0.33.1", features = ["cst"] }
pulldown-cmark = { version = "0.13.4", default-features = false }
regex = "1.13.1"
saphyr = "0.0.11"
semver = "1.0.28"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml_edit = "0.25.13"
ulid = "3.0.0"
ureq = { version = "3.3.0", features = ["json"] }

[dev-dependencies]
insta = "1.48.0"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
wiremock = "0.6.5"

[lints.rust]
unreachable_pub = "warn"
