[package]
name = "changesette"
version = "6.3.1"
edition = "2024"
rust-version = "1.88"
description = "A version and changelog manager using the changesets file format"
homepage = "https://github.com/iorate/changesette"
repository = "https://github.com/iorate/changesette"
license = "MIT"
keywords = ["changeset", "changelog", "versioning", "release", "semver"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive", "env"] }
dunce = "1.0.5"
fast-glob = "1.1.0"
file-id = "0.2.3"
inquire = "0.9.4"
jsonc-parser = { version = "0.33.1", features = ["cst"] }
petname = { version = "3.2.0", default-features = false, features = ["default-words"] }
pulldown-cmark = { version = "0.13.4", default-features = false }
rand = "0.10.2"
regex = "1.13.1"
saphyr = "0.0.12"
semver = "1.0.28"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
shell-words = "1.1.0"
tempfile = "3.27.0"
time = { version = "0.3.55", default-features = false }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["fmt"] }

[dev-dependencies]
insta = "1.48.0"

[lints.rust]
unreachable_pub = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
similar_names = "allow"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
